# You Podfile should look similar to this file. React Native currently does not support use_frameworks!
source 'https://github.com/CocoaPods/Specs.git'

platform :ios, '9.0'

target 'ChatBot' do

	# React deps podspec link
	pod 'React', :path => '../node_modules/react-native', :subspecs => [
		'Core',
		'CxxBridge',
		'DevSupport',
		'RCTActionSheet',
		'RCTAnimation',
		'RCTGeolocation',
		'RCTImage',
		'RCTLinkingIOS',
		'RCTNetwork',
		'RCTSettings',
		'RCTText',
		'RCTVibration',
		'RCTWebSocket',
	]

	# Third party React deps podspec link
	pod 'yoga', :path => '../node_modules/react-native/ReactCommon/yoga'
	pod 'DoubleConversion', :podspec => '../node_modules/react-native/third-party-podspecs/DoubleConversion.podspec'
	pod 'glog', :podspec => '../node_modules/react-native/third-party-podspecs/glog.podspec'
	pod 'Folly', :podspec => '../node_modules/react-native/third-party-podspecs/Folly.podspec'

	# react-native-maps dependencies
	pod 'react-native-maps', :path => '../node_modules/react-native-maps'
	pod 'react-native-google-maps', :path => '../node_modules/react-native-maps'
	pod 'GoogleMaps'
	pod 'Google-Maps-iOS-Utils'

	# react-native-vector-icons dependencies
	pod 'RNVectorIcons', :path => '../node_modules/react-native-vector-icons'

	# react-native-linear-gradient dependencies
	pod 'BVLinearGradient', :path => '../node_modules/react-native-linear-gradient'

end

post_install do |installer|
	installer.pods_project.targets.each do |target|
		if target.name == 'react-native-google-maps'
			target.build_configurations.each do |config|
				config.build_settings['CLANG_ENABLE_MODULES'] = 'No'
			end
		end
	end
end
